# Generated by Django 4.2.6 on 2024-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('mobile', models.BooleanField(max_length=15, verbose_name='mobilenumber')),
                ('password', models.CharField(max_length=15, verbose_name='password')),
            ],
        ),
    ]
